version: "3.9"
services:
  postgres:
    image: postgres:17-alpine
    container_name: jsonviz
    restart: always
    environment:
      POSTGRES_USER: jsonviz
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: jsonviz
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
